gvisor syscall test and add blocklist
occlum/gvisor pull request #1
Opened 2021-11-09 02:51 UTC by daan3601

* [ ] Have you followed the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)?
* [ ] Have you formatted and linted your code?
* [ ] Have you added relevant tests?
* [ ] Have you added appropriate Fixes & Updates references?
* [ ] If yes, please erase all these lines!

2021-11-09 03:01 UTC, jessehui requested changes
Please remove all the binaries and occlum_workspace dir

2021-11-09 03:01 UTC, jessehui commented on occlum/.__occlum_status
> +initialized
This file is not needed.

2021-11-09 03:01 UTC, jessehui commented on occlum/blocklist/aio_test
> +
Some files use one blank line to separate, some use two lines, some use three lines. What's the difference?

2021-11-09 03:01 UTC, jessehui commented on occlum/blocklist/socket_bind_to_device_sequence_test
> +
Don't put too many blank lines in the end.

2021-11-09 03:01 UTC, jessehui commented on occlum/sparefile/build_and_install_syscall_tests.sh
> +#!/bin/bash
Is this "sparefile" dir necessary?

2021-11-09 03:11 UTC, daan3601 commented on occlum/sparefile/build_and_install_syscall_tests.sh
> +#!/bin/bash
不是必要的，为了防止误删创建的

2021-11-09 03:12 UTC, daan3601 commented on occlum/blocklist/aio_test
> +
文件中间空格是区分阻塞的测试和失败的测试项的

2021-11-09 03:15 UTC, daan3601 commented on occlum/sparefile/build_and_install_syscall_tests.sh
> +#!/bin/bash
Not a necessary directory, in order to prevent unnecessary deletion when adding test items

2021-11-09 03:18 UTC, daan3601 commented on occlum/blocklist/aio_test
> +
The space is used to distinguish the test items that are blocked, the test items that are skipped, and the test items that fail.

2021-11-18 09:22 UTC, jessehui approved these changes
LGTM

2021-11-18 09:44 UTC, guzongmin approved these changes
LGTM

2021-11-18 09:44 UTC, merged