Optimized the run_occlum_passed_tests.sh script
occlum/gvisor pull request #4
Opened 2021-11-16 07:32 UTC by daan3601

* [ ] Have you followed the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)?
* [ ] Have you formatted and linted your code?
* [ ] Have you added relevant tests?
* [ ] Have you added appropriate Fixes & Updates references?
* [ ] If yes, please erase all these lines!

2021-11-16 07:56 UTC, jessehui requested changes

2021-11-16 07:56 UTC, jessehui commented on occlum/run_occlum_passed_tests.sh
> +BLOCKLIST_DIR=/blocklist/
This is absolute address still. Don't use absolute address.

2021-11-16 07:56 UTC, jessehui commented on occlum/run_occlum_passed_tests.sh
> +run_one_test(){
This function runs all the tests. This name is not suitable anymore.

2021-11-16 07:56 UTC, jessehui commented on occlum/run_occlum_passed_tests.sh
> +	FILTER=$(cat $BLOCKLIST_DIR/$1 | tr '\n' ':')
The indent is not good.

2021-11-17 09:39 UTC, jessehui commented
TEST

2021-11-18 02:42 UTC, jessehui commented on occlum/run_occlum_passed_tests.sh
> +occlum new occlum_workspace
What if there exists the occlum_workspace? Maybe delete the old occlum_workspace before creating new workspace.

2021-11-18 02:49 UTC, jessehui commented on occlum/run_occlum_passed_tests.sh
> +rm -rf occlum_workspace
Don't delete the workspace. This may needs inspection after finishing.

2021-11-18 09:24 UTC, jessehui approved these changes
LGTM

2021-11-18 09:45 UTC, guzongmin approved these changes
LGTM

2021-11-18 09:45 UTC, merged